### ISSUE TITLE
[REQ] license setting on GH

### ISSUE THREAD

**Issue by forart** [akashi-org/akashi#49]
Hi there, since we've collected your project in our [HyMPS lists](https://github.com/forart/HyMPS) (under the [Non-Linear Video Editors section](https://github.com/forart/HyMPS/blob/main/VideoNLEs.md)), can you please set licensing terms for your git ?

Our "problem" is that the badge service generates this: 

![](https://flat.badgen.net/github/license/akashi-org/akashi/?label=LICENSE)
(generating URL: https://flat.badgen.net/github/license/akashi-org/akashi/?label=LICENSE)

Thanks in advance.

**Comment by crux14** [comment]
As you may already know, this project has multiple licenses.
And in that case, I suppose badgen is unable to parse the license file properly.
There is something I could do, but the priority is relatively low as for now.

**Comment by forart** [comment]
OK, we've manually set the wording "MULTI" for akashi:

![](https://flat.badgen.net/badge/license/MULTI/blue?label=LICENSE)
(generating URL: https://flat.badgen.net/badge/license/MULTI/blue?label=LICENSE)

Thanks for your feedback.
